import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import Header from "./components/header";
import "./globals.css";

const outifit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Entertainment App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={outifit.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
